### ISSUE TITLE
passbolt.js requesting wrong path for config.json

### ISSUE THREAD

**Issue by rdavidso** [passbolt/passbolt#10]
The config.json is requesting the path `/app/webroot/js/app/config/config.json` when it should just be requesting `/js/app/config/config.json`  And the same is true for `notification.json`

**Comment by stripthis** [comment]
Hello @rdavidso, thanks for spotting this one!

@cedricalfonsi I think you introduced this one with PASSBOLT-1419, so I'm assigning this one to you.

**Comment by stripthis** [comment]
ref. PASSBOLT-1599

**Comment by cedricalfonsi** [comment]
The issue will be fixed with the next release 1.0.13.
@rdavidso thanks for your support

**Comment by stripthis** [comment]
This fix was not released as part of 1.0.13. Fix pending.

**Comment by stripthis** [comment]
Fixed as part of 1.0.14 released today. Feel free to reopen the ticket if needed.
