### ISSUE TITLE
ControllerLog do not accept IPV6 addresses

### ISSUE THREAD

**Issue by tomamplius** [passbolt/passbolt#11]
I can't connnect to my passbolt instance with ipv6.
Thé main message is internal error. In thé debug mode thé issue is an error on thé log controler because it can't store the ip v6 format

**Comment by stripthis** [comment]
Thank you for reporting this important issue @tomamplius. We'll look into adding a fix into the next release.

**Comment by stripthis** [comment]
ref. PASSBOLT-1601

**Comment by stripthis** [comment]
@tomamplius the latest release v1.0.13 should fix this issue. Let us know if you still have troubles.
