### ISSUE TITLE
The GPG Server key defined in the config is not found in the gpg keyring

### ISSUE THREAD

**Issue by anogues** [passbolt/passbolt#12]
Hello.

I am getting htis error now. Any help?

2016-07-14 12:28:37 Error: [CakeException] The GPG Server key defined in the config is not found in the gpg keyring
Request URL: /auth/login
Stack Trace:
#0 /var/www/passbolt/app/Controller/Component/Auth/GpgAuthenticate.php(52): GpgAuthenticate->_initKeyring()
#1 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(766): GpgAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#2 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(611): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#3 /var/www/passbolt/app/Controller/AuthController.php(35): AuthComponent->login()
#4 [internal function]: AuthController->login()
#5 /var/www/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AuthController), Array)
#6 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#8 /var/www/passbolt/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

And when i list the keys i see them

[root@localhost .gnupg]# gpg --list-secret-keys
/root/.gnupg/secring.gpg
------------------------
sec   1024R/C8C161D6 2016-07-13
uid                  passbolt <xxx@xxx>
ssb   1024R/336082AA 2016-07-13

sec   4096R/573EE67E 2015-10-26 [expires: 2019-10-26]
uid                  Passbolt Server Test Key <no-reply@passbolt.com>
ssb   4096R/D0A5D96B 2015-10-26

I know the keyring should be in the /root but i am just testing it.

Albert.

**Comment by kevinmuller** [comment]
Hi Albert,

The GPG keyring used by Apache might not be the same used by your root user. On a default debian installation, the keyring used by apache is in the directory /home/www-data/.gnupg/
Could you cross check what user your apache is running as ? 

Another reason why this is happening could be that you installed passbolt as root, and that the permissions of the www-data gpg keyring are now incorrect. Could you try the solution described in the section "Why am I getting a segmentation fault at install?" in our [installation help page](https://www.passbolt.com/help/tech/install).  It consists of resetting the permissions of the keyring.

Let me know if this helps.

Kevin

**Comment by anogues** [comment]
Hello Kevin.

I am using Centos7 but i check your suggestions and come back to you.

Many Thanks for your help.
Albert.

**Comment by anogues** [comment]
No way. it does not work.

I can install and configure the plugin but then it fails.

Also the last step of the plugin configuration fails because there is no default value for the active column. But not sure this has anything to do with it.

**Comment by anogues** [comment]
},
    "response": {
      "header": {
        "id": "9bf47528-77ef-3d3f-aefc-2c398e536538",
        "status": "error",
        "title": "app_users_validateaccount_error",
        "servertime": 1468519097,
        "controller": "users",
        "action": "validateAccount",
        "message": "SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'active' at row 1"
      }
    }
  }
}

**Comment by stripthis** [comment]
Sorry to hear about that @anogues. This seems to be related to the schema issues you reported in the other thread and the modification you made to the schema following with the suggestion from the other user. We'll work on a fixing the other issue this week so that you can retry with a fresh install next week.

**Comment by anogues** [comment]
Perfect. That would be good. We like the app and will suit our needs so hope we can get it to work.

In the meantime i am trying installing all the stack with the bitnami lamp package instead of doing it manually. Maybe it works this time...

Many thanks and keep the good work
Albert

**Comment by anogues** [comment]
Hello Some News.

After removing the STRICT_MODE directive in the my.cnf file now no issues. The user gets created and no errors any more.

Now I am facing a problem logging in with the user. When logging the progress bar appears and it never ends...

loading, please wait...

I can see the following in the log:

[Fri Jul 15 13:20:11.431867 2016] [core:notice] [pid 2169] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Fri Jul 15 13:20:11.433069 2016] [suexec:notice] [pid 2169] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Jul 15 13:20:11.472803 2016] [auth_digest:notice] [pid 2169] AH01757: generating secret for digest authentication ...
[Fri Jul 15 13:20:11.473735 2016] [lbmethod_heartbeat:notice] [pid 2169] AH02282: No slotmem from mod_heartmonitor
[Fri Jul 15 13:20:11.547321 2016] [mpm_prefork:notice] [pid 2169] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Fri Jul 15 13:20:11.547395 2016] [core:notice] [pid 2169] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'


It is very weird as selinux has been disabled but i keep checking...

**Comment by stripthis** [comment]
@anogues we released a fix for Mysql57, please see the other ticket. Let me know if you have another issue by reopening this one or by creating a new one. Thanks for your help!
