### ISSUE TITLE
nginx config

### ISSUE THREAD

**Issue by infectormp** [passbolt/passbolt#15]
Hello,
can you provide nginx config for passbolt?

**Comment by stripthis** [comment]
Hi @infectormp,

We haven't tried running Passbolt on nginx yet, but I should work like any Cakephp application. Maybe you can have a shot at following the Cakephp documentation and tell us how it went?
http://book.cakephp.org/2.0/en/installation/url-rewriting.html#pretty-urls-on-nginx

Thanks a lot for trying out passbolt!

**Comment by infectormp** [comment]
@stripthis, thanks for the info.

default nginx config work fine with this addition

```
    location / {
        try_files $uri $uri/ /$1/index.php?$args;
    }
```

**Comment by mannp** [comment]
@infectormp interested to know if you hardened the config at all?

I am conscious of the data passbolt is holding but want to utilise the sharing via my domain.

**Comment by infectormp** [comment]
@mannp full config

```
server {
    listen 80;
    server_name xxx.xx;

    return 301 https://$server_name$request_uri;  # enforce https

}

server {
    listen 443 ssl http2;
    server_name xxx.xx;

    access_log /var/log/nginx/passbolt.access_log;
    error_log /var/log/nginx/passbolt.error_log;

    root /var/www/localhost/htdocs/passbolt/app/webroot/;

    include /etc/nginx/ssl.d/wc.ssl.conf;

    location / {
        try_files $uri $uri/ /$1/index.php?$args;
    }

    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass  unix:/run/php-fpm/www_71.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
```

**Comment by mannp** [comment]
Thanks @infectormp much appreciated.
