### ISSUE TITLE
Description length is a bit short

### ISSUE THREAD

**Issue by LegendPJ** [passbolt/passbolt#18]
Hi,

During the creation of a password, we can set a description, but the field in which we can put information is limited by the interface.
When I've looked into the database, I've seen that the type of this field is "TEXT", so I don't understand why there's this limitation.

Thank's

**Comment by kevinmuller** [comment]
Hi @LegendPJ ,

You are actually not the first one to report this problem, but somehow we never managed to understand what was exactly the problem. In my interface, the description field is multilines (cf screenshot).

<img width="478" alt="screen shot 2016-09-16 at 16 36 24" src="https://cloud.githubusercontent.com/assets/80405/18589671/0e766a80-7c2c-11e6-9e27-81c6225634ca.png">

Could you send me a screenshot of what you see at your end?

Thanks.
Kevin

**Comment by LegendPJ** [comment]
Hi,

The problem is not the height of the textarea, but his "maxlength" attribute.
As you can see in this screenshot, the lorem ipsum is not fully written.

Thanks.

PJ



Pierre Julien MARTINEZ

**Comment by kevinmuller** [comment]
Alright!! Now I got it!
Looks like we also have a similar bug for URI, and that bug is also in the current sprint ! So we'll take care of the description one in the meantime.
Reference: PASSBOLT-1658

Thanks for reporting!

Kevin

**Comment by LegendPJ** [comment]
So cool !
I’ve juste noticed that the textarea is also limited by a constraint (see screenshot).
Only 255 caracters seems to be a little short for some descriptions, but maybe this constraint of 255 caracters is here for a very good reason.

Thanks

PJ

**Comment by stripthis** [comment]
@LegendPJ We have fixed this issue in release v.1.2.0. Thanks,
