### ISSUE TITLE
Changing documentation license to be open source-compliant

### ISSUE THREAD

**Issue by Calinou** [passbolt/passbolt#2]
As noticed on [Linuxfr](https://linuxfr.org/news/passbolt-un-nouveau-gestionnaire-de-mots-de-passe-pour-les-equipes) (French), the documentation license Passbolt uses is CC BY-NC-SA, which does not follow the [Open Source Definition](https://opensource.org/osd).

Would you please consider changing it to a free license like CC BY-SA or CC BY? Many open source projects like [Bootstrap](https://github.com/twbs/bootstrap) already use CC BY 3.0 for their documentation, so it could make sense to go CC BY, but going CC BY-SA also makes sense since the code is under a copyleft license as well.

**Comment by stripthis** [comment]
Hello, thank you for your feedback. We have updated our [terms and conditions](https://www.passbolt.com/terms) and you can now see that the documentation and any other content on our website is now available as [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). Have a great day!
