### ISSUE TITLE
Error "The server was unable to respect the authentication protocol." Some GPGAuth headers are transformed to lower case.

### ISSUE THREAD

**Issue by veisis** [passbolt/passbolt#24]
Error message: The server was unable to respect the authentication protocol.
Tested on my server and Passbolt demo page.

**Comment by stripthis** [comment]
Hello, 

@veisis can you tell us a bit more about your server configuration? Are using nginx by any chance? Thanks a lot for trying out passbolt!

**Comment by veisis** [comment]
Yes we are using nginx. But same error i get in https://demo.passbolt.com/ page. From what i can tell that server is running with Apache.

**Comment by stripthis** [comment]
@veisis can you me the http headers you are getting on demo.passbolt.com?
Thanks,

![screen shot 2016-10-07 at 12 20 07](https://cloud.githubusercontent.com/assets/77410/19181168/cc822296-8c88-11e6-9423-829028f762c2.png)

**Comment by veisis** [comment]
Screenshot of response:
![screenshot_1](https://cloud.githubusercontent.com/assets/4570512/19182309/3b811052-8c7b-11e6-9eb1-16af0d5f82c2.png)

**Comment by stripthis** [comment]
It's very strange, something is affecting the capitalization of the some of the HTTP headers like x-gpgauth-authenticated. While it's not the same than #16 (where all the headers are lower case).  We have a fix for this, it will be solved at the same time in the next release, we are finalizing the QA.

**Comment by stripthis** [comment]
Hi @veisis, this issue has been fixed in release v1.2.0. Feel free to reopen this ticket if the problem persists on your end.
