### ISSUE TITLE
Security review

### ISSUE THREAD

**Issue by SudoHenk** [passbolt/passbolt#4]
Did the project already had a security review?

**Comment by stripthis** [comment]
Some of the components have already been reviewed:
- The firefox plugin have been reviewed as part of the normal marketplace process. 
- Opengpgjs been reviewed by Cure53 in 2014. 
- Cakephp v2.x have been under scrutiny for years.

Obviously this is far from perfect and organizing more regular independent 3rd party audits is one of our main priorities.
