### ISSUE TITLE
Mass/Bulk Share

### ISSUE THREAD

**Issue by dannygu** [passbolt/passbolt#8]
Hi,

I wonder if i am missing something or its not possible yet, is there an option to bulk share ? I have a few passwords stored and i'd like to share them all with another user  but i can only choose one at a time to share.

Thanks for a great project.

Danny.

**Comment by stripthis** [comment]
Hello Danny,

Indeed this feature is not available at the moment. In the future we are planning to enable sharing in bulk using password categories or groups (or also by selecting multiple passwords via the checkboxes and clicking share). See our roadmap: https://www.passbolt.com/roadmap

Thanks for trying out passbolt!
